# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90f8567e3116c1715c55dfe191fb8b79a6bda51626694546149e199443feb22c4eb2f9d27a1a4bd1c7b6df5bf9d71a80c5c435715dd50aa6884ad270e760ba3d

test:
  secret_key_base: 8f224f578aff4bde5256c76e9b1cf0ee9b9c1d7eb98275f2c57bfb2b5f52031d36b10ed9d92d97c77f0ba493c874879901204f17c3af82eb3516099fcb8dc456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
